### ISSUE TITLE
Find emoji lexicon

### ISSUE THREAD

**Issue by hendraet** [imackerracher/NLP-Task#3]

**Comment by SofiyaDemchuk** [comment]
List of emoticons (with meaning) used in paper: https://en.wikipedia.org/wiki/List_of_emoticons;
Emoticon Sentiment Lexicon, but the sentiment of an emoticon is either -1 (negative), 0 (neutral), or 1 (positive): https://www.w3.org/community/sentiment/wiki/Datasets#Emoticon_Sentiment_Lexicon

...SEARCHING...

USEFUL: http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0144296# - not only -1, 0, 1, but the range between those values (e.g. the neutrality can range between 0 and 0.5) _???implementation???_

**Comment by SofiyaDemchuk** [comment]
The Sentiment140 Lexicon was created from the Sentiment140 emoticon corpus of 1.6 million tweets and contains a list of words and their associations with positive and negative sentiment:
https://github.com/felipebravom/StaticTwitterSent/tree/master/extra/Sentiment140-Lexicon-v0.1

**Comment by SofiyaDemchuk** [comment]
Better list: http://unicode.org/emoji/charts/emoji-list.html
